server:
  port: 8003 # 服务端口
spring:
  application:
    name: service-vod # 服务名 不要加_不然容易出问题
  profiles:
    active: dev # 环境设置：dev、test、prod
  servlet:
    multipart:
      max-file-size: 1024MB # 最大上传单个文件大小：默认1M
      max-request-size: 1024MB # 最大置总上传的数据大小 ：默认10M
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#阿里云 vod
#不同的服务器，地址不同
aliyun:
  vod:
    file:
      keyid: LTAI4G1y8HNgY1g5mmkg3UHi
      keysecret: BGlANc9HO4DHFlSgY9Ztqka7NqQmwa
