# 服务端口
server:
  port: 8150

# 服务名
spring:
  application:
    name: service-ucenter
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/csy/educenter/mapper/xml/*.xml

#mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

wx:
  open:
    # 微信开放平台appId
    appId: wxed9954c01bb89b47
    # 微信开放平台 appsecret
    appSecret: a7482517235173ddb4083788de60b90e
    # 微信开放平台 重定向url
    redirectUrl: http://guli.shop/api/ucenter/wx/callback


